services:
  backend:
    user: "0:0"
    command: ["sleep", "infinity"]
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      disable: true

  frontend:
    user: "0:0"
    command: ["sleep", "infinity"]
    depends_on: []
    healthcheck:
      disable: true
